ui: tape
browsers:
  - name: chrome
    version: 30..latest

  # - name: safari
  #   version: latest

  # - name: ie
  #   version: 9..latest

  - name: firefox
    version: 25..latest

server: ./test/server.js